### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Heater711** [Special-K-s-Flightsim-Bots/DCSServerBot#8]
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DCSServerBot-2.2.0\cogs\agent.py", line 158, in init
    if (('AUTOSTART_DCS' in self.bot.config[installation]) and (self.bot.config.getboolean(installation, 'AUTOSTART_DCS') is True)):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'caucaso'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DCSServerBot-2.2.0\cogs\agent.py", line 164, in init
    if (('AUTOSTART_SRS' in self.bot.config[installation]) and (self.bot.config.getboolean(installation, 'AUTOSTART_SRS') is True)):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'caucaso'
```

**Comment by karel26** [comment]
It looks like it searches an installation with the name "caucaso" in the dcsserverbot.ini file and does not find it.
You need a section for every server that is named like the installation, e.g. 

[caucaso]
DCS_HOST = 127.0.0.1
DCS_PORT = 6667
DCS_HOME = %%USERPROFILE%%\\Saved Games\\caucaso
SRS_CONFIG = %%USERPROFILE%%\\Saved Games\\caucaso\\Config\\SRS.cfg
SRS_HOST = 127.0.0.1
SRS_PORT = 5002
AUTOSTART_DCS = true
AUTOSTART_SRS = true
STATISTICS = true
