### ISSUE TITLE
V 2.5.2

### ISSUE THREAD

**Issue by Heater711** [Special-K-s-Flightsim-Bots/DCSServerBot#9]
Bot Version - Dev 2.5.2 | Py 3.8

```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DCSServerBot-development\core\__init__.py", line 1, in <module>
    from .bot import *
  File "C:\Users\Administrator\Desktop\DCSServerBot-development\core\bot.py", line 12, in <module>
    from .listener import EventListener
  File "C:\Users\Administrator\Desktop\DCSServerBot-development\core\listener.py", line 6, in <module>
    class EventListener:
  File "C:\Users\Administrator\Desktop\DCSServerBot-development\core\listener.py", line 18, in EventListener
    async def processEvent(self, data: dict[str, Union[str, int]]) -> None:
TypeError: 'type' object is not subscriptable
```

**Comment by karel26** [comment]
Hm, that might be because of Python 3.8Would you mind upgrading to 3.9? Think that's what's listed in the requirements and I use this version.Am 25.12.2021 11:13 schrieb Heater711 ***@***.***>:
Bot Version - Dev 2.5.2 | Py 3.8
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DCSServerBot-development\core\__init__.py", line 1, in <module>
    from .bot import *
  File "C:\Users\Administrator\Desktop\DCSServerBot-development\core\bot.py", line 12, in <module>
    from .listener import EventListener
  File "C:\Users\Administrator\Desktop\DCSServerBot-development\core\listener.py", line 6, in <module>
    class EventListener:
  File "C:\Users\Administrator\Desktop\DCSServerBot-development\core\listener.py", line 18, in EventListener
    async def processEvent(self, data: dict[str, Union[str, int]]) -> None:
TypeError: 'type' object is not subscriptable
